### ISSUE TITLE
Absence of some related files

### ISSUE THREAD

**Issue by feiyuxiaoThu** [codezs09/l2_frenet_planner#12]
Thanks for your nice work and the well-organized code!
I tried to reproduce your results but met with some errors:

1. the file 'config/scenes/one_lane_slow_down.json' used in main.cpp is missing.
2. the file 'FrenetOptimalTrajectory/fot.py ' is also missing.

And I run the script according to your ReadMe '' and get the following errors:

`ob lane_ids: [0]
ob lane_ids: [0]
ob lane_ids: [1]
Segmentation fault
Command failed with error 139`

**Comment by codezs09** [comment]
Hi Feiyu, thanks for the interest! Regarding your question:

1. you are right. I renamed the file to "slow_down.json" which is under "config/scenes". Other scenes defined under this directory please also feel free to try. But since we are using the wrapper "scripts/fot_v2.py" to run the file, it would not affect the results and you don't need to make any modifications to fix the route.
2. Should be "scripts/fot_v2.py". Please use this wrapper to run the program instead of the bin for main.cpp file. 

I have updated the Readme.md. Please use "python3.8 scripts/fot_v2.py --local_planning" to reproduce the results. 
Let me know if you met any troubles.
